name: DevSecOps Pipeline
on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_HOST: ${{ secrets.JF_URL_HOST }}
      IMAGE: ${{ secrets.JF_URL_HOST }}/docker-local/spring-petclinic:${{ github.run_number }}
      BUILD_NAME: spring-petclinic
      BUILD_NUMBER: ${{ github.run_number }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          custom-server-id: local-artifactory
          disable-auto-build-publish: true  # We want to do it manually at the end
      
      - name: Configure JFrog Maven
        run: |
          # note 'maven-central' is a Remote Repo in JFrog pointing to real maven central
          jf mvn-config --server-id-deploy local-artifactory \
            --server-id-resolve local-artifactory \
            --repo-resolve-releases maven-central \
            --repo-resolve-snapshots maven-central \
            --repo-deploy-releases maven-local \
            --repo-deploy-snapshots maven-local

      - name: Compile and Test
        run: jf mvn clean install -DskipTests=false --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER

      - name: Docker Login
        run: jf docker login --server-id local-artifactory
        
      - name: Build Docker Image
        run: docker build -t $IMAGE .

      - name: Scan Local Image with Xray
        run: jf docker scan $IMAGE --format=json > xray-scan-results.json
      
      - name: Publish to Artifactory
        run: jf docker push $IMAGE --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER
          
      - name: Publish Build Info to JFrog
        run : |
          jf rt build-collect-env $BUILD_NAME $BUILD_NUMBER
          jf docker add-build $IMAGE $BUILD_NAME $BUILD_NUMBER
          jf rt build-publish $BUILD_NAME $BUILD_NUMBER
      
      - name: Scan Image in repository with Xray 
        run: jf bs $BUILD_NAME $BUILD_NUMBER --format=json > xray-build-scan.json
          
      - name: Upload Scan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xray-reports
          path: |
            xray-scan-results.json
            xray-build-scan.json
