name: DevSecOps Pipeline
on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          server-id: local-artifactory
          username: walaj@waland.net
      
      - name: Configure JFrog Maven
        run: |
          # This configures the project to resolve via JFrog
          jf mvn-config --server-id-deploy default \
            --server-id-resolve default \
            --repo-resolve-releases maven-remote \
            --repo-resolve-snapshots maven-remote \
            --repo-deploy-releases maven-local \
            --repo-deploy-snapshots maven-local

      - name: Compile and Test
        run: jf mvn clean install --build-name=spring-petclinic --build-number=${{ github.run_number }} --server-id=local-artifactory

      - name: Docker Login
        run: jf docker login

      - name: Build Docker Image
        run: docker build -t ${{ secrets.JF_URL_HOST }}/docker-local/spring-petclinic:${{ github.run_number }} .

      - name: Publish to Artifactory
        run: |
          # Scan and push the image
          jf docker push ${{ secrets.JF_URL_HOST }}/docker-local/spring-petclinic:${{ github.run_number }}
          
          # Collect build info for Xray
          jf rt build-publish spring-petclinic ${{ github.run_number }}
